[package]
authors = ["Victor Koenders <victor.koenders@gmail.com>"]
name = "foodorder_bot"
version = "0.1.0"

[dependencies]
irc = { version = "0.13", features = ["json"] }
lazy_static = "1.2"
chrono = "0.4"
